[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
license = "MIT/Apache-2.0"
name = "quickcheck_derive"
version = "0.1.0"

[dependencies]
quote = "0.3.15"
syn = "0.11.11"

[dev-dependencies]
quickcheck = "0.4.1"
rand = "0.3.16"

[lib]
proc_macro = true
